const constant = {
	// HTTP Status code.
	SUCCESS_STATUS_CODE: 200,
	VALIDATION_STATUS_CODE: 400,
	RECORD_NOT_FOUND_STATUS_CODE: 404,
	SOMETHING_WENT_WRONG_STATUS_CODE: 500,

    APP_PATH: "/var/www/html/",
    BASEURL: "https://syked.co.za/",
    TOKEN_VALUE: "syked123456qwerty",
    
    // Messages.
    SOMETHING_WENT_WRONG: "Something went wrong. Please, try again, if issue persist. Please, report to support team for further help.",
    LOGIN_SUCCESS: "Logged in successful.",
    UPDATE_SUCCESS: "Profile has been updated successful.",
    IMAGE_UPLOAD_SUCCESS: "Image has been uploaded successful.",
    IMAGE_UPLOAD_FAIL: "Image has been not uploaded successful.",
    INVALID_CREDENTIALS: "Invalid credentials.",
    PASSWORD_CHANGE_SUCCESS: "Password has been changed successful.",
    PASSWORD_CHANGE_FAIL: "Password not changed.",
    PASSWORD_RESET_MESSAGE: "If this email is registered with us, You will receive an email containing the password reset instructions.",
    EMAIL_NOT_REGISTER: "This email is not registered.",
    RECORD_NOT_FOUND: "Record not found.",
    STATUS_ON_CHANGE: "Status STATUS successful.",
    EMAIL_SUCCESS: "Email has been sent successful.",
    NOTIFICATION_SUCCESS: "Notification has been sent successful.",
    THERAPIST_PROFILE_STATUS: "Therapist profile has been STATUS.",
    ADD_QUESTION: "Question has been added successful.",
    EDIT_QUESTION: "Question has been updated successful.",
    DELETE_QUESTION: "Question has been deleted successful.",
    DELETE_NOTIFICATION: "Notification has been deleted successful.",
    ADD_PROMO_CODE: "Promo code has been created successful.",
    EDIT_CONFIGURATION:"Configuration has been saved successful.",
    EDIT_CONTENT_SUCCESS: "Content has been updated successful.",
    DELETE_USER: "User has been deleted successful.",
    DELETE_VIDEO_PLAN: "Video plan has been deleted successful.",
    ADD_VIDEO_PLAN: "Video plan has been created successful.",
    EDIT_VIDEO_PLAN: "Video plan has been updated successful.",
    EDIT_BOOK_SUCCESS:"Request has been updated successful",

    // Validations.
    TOKEN_VALIDATION: "Token required.",
    EMAIL_VALIDATION: "Email is required.",
    PASSWORD_VALIDATION: "Password is required.",
    CURRENT_PASSWORD_VALIDATION: "Current password is required.",
    NEW_PASSWORD_VALIDATION: "New password is required.",
    CONFIRM_PASSWORD_VALIDATION: "Confirm password is required.",
    ID_VALIDATION: "ID is required.",
    STATUS_VALIDATION: "Status is required.",
    TO_USER_EMAIL_VALIDATION: "To user email is required.",
    SUBJECT_VALIDATION: "Subject is required.",
    MESSAGE_VALIDATION: "Message is required.",
    QUESTION_VALIDATION: "Question is required.",
    THERAPY_TYPE_VALIDATION: "Therapy type is required.",
    QUESTION_TYPE_VALIDATION: "Question type is required.",
    OPTIONS_VALIDATION: "Options are required.",
    TITLE_VALIDATION: "Title is required.",
    CODE_VALIDATION: "Code is required.",
    MIN_PRICE_VALIDATION: "Minimum price is required.",
    MAX_DISCOUNT_VALIDATION: "Maximum discount is required.",
    DISCOUNT_TYPE_VALIDATION: "Discount type is required.",
    DISCOUNT_AMT_VALIDATION: "Discount amount is required.",
    VALID_FROM_VALIDATION: "Valid from date is required.",
    VALID_TILL_VALIDATION: "Valid till date is required.",
    MAX_USES_VALIDATION: "Maximum uses is required.",
    MAX_USES_PER_PERSON_VALIDATION: "Maximum uses per person is required.",
    COMMISSION_VALIDATION: "Commission is required.",
    REFERRAL_DISCOUNT_VALIDATION: "Referral discount is required.",
    CONTENT_VALIDATION: "Content is required.",
    DESCRIPTION_VALIDATION: "Description is required.",
    PRICE_VALIDATION: "Price is required.",
    MINUTES_VALIDATION: "Minutes is required.",
};

// export module pool to be used in other files
module.exports = Object.freeze(constant);
